### ISSUE TITLE
On Selection callback via props

### ISSUE THREAD

**Issue by jptarqu** [syncfusion/ej2-react-dropdowns#1]
In normal react with regular html, we can do:

`<input onChange={(evt) => myFuncnotifyOfChg(evt.target.value)} /> `

so that we know when the text changed in the input box. Can we have something similar for the callback for the ej2 dropdown for when a value is selected? Maybe something like:

`<DropDownListComponent onChange={(evt) => myFuncnotifyOfChg(evt.target.value)} /> `

**Comment by thangavele** [comment]
Hi Jptarqu,

Thanks for using Syncfusion components.

Query: The callback for the ej2 dropdown for when a value is selected?

We can get the selected value of DropDownList on [change](http://ej2.syncfusion.com/react/documentation/drop-down-list/api-dropDownListComponent.html#change-emittypechangeeventargs) event same like your requirement. 

**Render DropDownList component:**

`
  <DropDownListComponent id="ddl" **change={(event) => this.onChange(event)}** placeholder="Select a game" dataSource={this.data} fields={this.fields} />

`

**Change event Callback function:**
` 
onChange(event: ChangeEventArgs | undefined) {
    alert((event as ChangeEventArgs).itemData[this.fields.text as string]);
}

`

For your reference, we have prepared the simple sample in plunker. Please get the sample in the below link, 

**Demo link**: http://plnkr.co/edit/hyUENtOwXVoCBNnNSHyd?p=preview 

Please let me know if you have any queries. 


Regards,
Thangavel E
